import { TimerConfig } from './types';

export const TRANSLATIONS = {
  es: {
    mainTitle: "Debate Escolar",
    subtitle: "ikasNOVA",
    configTitle: "Configuración de Participantes",
    labelTeamA: "Equipo / Participante A:",
    labelTeamB: "Equipo / Participante B:",
    placeholderA: "Nombre del equipo A",
    placeholderB: "Nombre del equipo B",
    startDebate: "Iniciar Debate",
    intro1: "Introducción Equipo A",
    intro2: "Introducción Equipo B",
    ref1_1: "Refutación 1 Equipo A",
    ref1_2: "Refutación 1 Equipo B",
    ref2_1: "Refutación 2 Equipo A",
    ref2_2: "Refutación 2 Equipo B",
    concl1: "Conclusión Equipo A",
    concl2: "Conclusión Equipo B",
    initialMinutes: "Tiempo inicial (min):",
    warningSeconds: "Aviso en (seg):",
    start: "Iniciar",
    pause: "Pausar",
    reset: "Reiniciar",
    export: "Exportar Tiempos a CSV",
    timeFinished: "¡Tiempo finalizado para",
    enterNames: "Por favor, introduce los nombres de ambos equipos o participantes.",
    completed: "Completado",
    yes: "Sí",
    no: "No",
    finishDebate: "Finalizar Debate",
    debateResults: "Resultados del Debate",
    totalTime: "Tiempo Total Utilizado",
    totalOvertime: "Tiempo Extra Total",
    newDebate: "Nuevo Debate",
    phase: "Fase",
    timeUsed: "Tiempo Usado",
    overtime: "Tiempo Extra",
    // Accessibility additions
    minute: "minuto",
    minutes: "minutos",
    second: "segundo",
    seconds: "segundos",
    and: "y",
    timeRemaining: "Tiempo restante",
    warningMessage: "Aviso, el tiempo se está acabando",
  },
  en: {
    mainTitle: "School Debate",
    subtitle: "ikasNOVA",
    configTitle: "Participant Configuration",
    labelTeamA: "Team / Participant A:",
    labelTeamB: "Team / Participant B:",
    placeholderA: "Team A name",
    placeholderB: "Team B name",
    startDebate: "Start Debate",
    intro1: "Introduction Team A",
    intro2: "Introduction Team B",
    ref1_1: "Rebuttal 1 Team A",
    ref1_2: "Rebuttal 1 Team B",
    ref2_1: "Rebuttal 2 Team A",
    ref2_2: "Rebuttal 2 Team B",
    concl1: "Conclusion Team A",
    concl2: "Conclusion Team B",
    initialMinutes: "Initial time (min):",
    warningSeconds: "Warning at (sec):",
    start: "Start",
    pause: "Pause",
    reset: "Reset",
    export: "Export Times to CSV",
    timeFinished: "Time finished for",
    enterNames: "Please enter the names of both teams or participants.",
    completed: "Completed",
    yes: "Yes",
    no: "No",
    finishDebate: "Finish Debate",
    debateResults: "Debate Results",
    totalTime: "Total Time Used",
    totalOvertime: "Total Overtime",
    newDebate: "New Debate",
    phase: "Phase",
    timeUsed: "Time Used",
    overtime: "Overtime",
    // Accessibility additions
    minute: "minute",
    minutes: "minutes",
    second: "second",
    seconds: "seconds",
    and: "and",
    timeRemaining: "Time remaining",
    warningMessage: "Warning, time is running out",
  },
  eu: {
    mainTitle: "Eskola Eztabaida",
    subtitle: "ikasNOVA",
    configTitle: "Parte-hartzaileen Konfigurazioa",
    labelTeamA: "A Taldea / Parte-hartzailea:",
    labelTeamB: "B Taldea / Parte-hartzailea:",
    placeholderA: "A taldearen izena",
    placeholderB: "B taldearen izena",
    startDebate: "Eztabaida Hasi",
    intro1: "Sarrera A Taldea",
    intro2: "Sarrera B Taldea",
    ref1_1: "Ezeztapena 1 A Taldea",
    ref1_2: "Ezeztapena 1 B Taldea",
    ref2_1: "Ezeztapena 2 A Taldea",
    ref2_2: "Ezeztapena 2 B Taldea",
    concl1: "Ondorioa A Taldea",
    concl2: "Ondorioa B Taldea",
    initialMinutes: "Hasierako denbora (min):",
    warningSeconds: "Abisua (seg):",
    start: "Hasi",
    pause: "Gelditu",
    reset: "Berrezarri",
    export: "Denbora CSV-ra Esportatu",
    timeFinished: "Denbora amaitu da",
    enterNames: "Mesedez, sartu bi talde edo parte-hartzaileen izenak.",
    completed: "Osatuta",
    yes: "Bai",
    no: "Ez",
    finishDebate: "Eztabaida Amaitu",
    debateResults: "Eztabaidaren Emaitzak",
    totalTime: "Erabilitako Denbora Guztira",
    totalOvertime: "Aparteko Denbora Guztira",
    newDebate: "Eztabaida Berria",
    phase: "Fasea",
    timeUsed: "Erabilitako Denbora",
    overtime: "Aparteko Denbora",
    // Accessibility additions
    minute: "minutu",
    minutes: "minutu",
    second: "segundo",
    seconds: "segundo",
    and: "eta",
    timeRemaining: "Geratzen den denbora",
    warningMessage: "Abisua, denbora agortzen ari da",
  }
};

export const TIMER_CONFIGS: TimerConfig[] = [
  { id: 'intro1', defaultMinutes: 3, defaultWarning: 30, team: 'A' },
  { id: 'intro2', defaultMinutes: 3, defaultWarning: 30, team: 'B' },
  { id: 'ref1_1', defaultMinutes: 4, defaultWarning: 30, team: 'A' },
  { id: 'ref1_2', defaultMinutes: 4, defaultWarning: 30, team: 'B' },
  { id: 'ref2_1', defaultMinutes: 4, defaultWarning: 30, team: 'A' },
  { id: 'ref2_2', defaultMinutes: 4, defaultWarning: 30, team: 'B' },
  { id: 'concl1', defaultMinutes: 3, defaultWarning: 30, team: 'A' },
  { id: 'concl2', defaultMinutes: 3, defaultWarning: 30, team: 'B' },
];
