
import { TimerConfig } from './types';

export const TRANSLATIONS = {
  es: {
    mainTitle: "Debate escolar",
    subtitle: "ikasNOVA",
    configTitle: "Configuración de participantes",
    labelTeamA: "Equipo / participante A:",
    labelTeamB: "Equipo / participante B:",
    placeholderA: "Nombre del equipo A",
    placeholderB: "Nombre del equipo B",
    startDebate: "Iniciar debate",
    intro1: "Introducción equipo A",
    intro2: "Introducción equipo B",
    ref1_1: "Refutación 1 equipo A",
    ref1_2: "Refutación 1 equipo B",
    ref2_1: "Refutación 2 equipo A",
    ref2_2: "Refutación 2 equipo B",
    concl1: "Conclusión equipo A",
    concl2: "Conclusión equipo B",
    initialMinutes: "Tiempo inicial (min):",
    warningSeconds: "Aviso en (seg):",
    start: "Iniciar",
    pause: "Pausar",
    reset: "Reiniciar",
    export: "Exportar tiempos a CSV",
    exportPDF: "Exportar resultados a PDF",
    timeFinished: "¡Tiempo finalizado para",
    enterNames: "Por favor, introduce los nombres de ambos equipos o participantes.",
    completed: "Completado",
    yes: "Sí",
    no: "No",
    finishDebate: "Finalizar debate",
    debateResults: "Resultados del debate",
    totalTime: "Tiempo total utilizado",
    totalOvertime: "Tiempo extra total",
    newDebate: "Nuevo debate",
    phase: "Fase",
    timeUsed: "Tiempo usado",
    overtime: "Tiempo extra",
    // Accessibility additions
    minute: "minuto",
    minutes: "minutos",
    second: "segundo",
    seconds: "segundos",
    and: "y",
    timeRemaining: "Tiempo restante",
    warningMessage: "Aviso, el tiempo se está acabando",
    fullScreen: "Pantalla completa",
    exitFullScreen: "Salir de pantalla completa",
    totalCombinedTime: "Tiempo total acumulado",
  },
  en: {
    mainTitle: "School debate",
    subtitle: "ikasNOVA",
    configTitle: "Participant configuration",
    labelTeamA: "Team / participant A:",
    labelTeamB: "Team / participant B:",
    placeholderA: "Team A name",
    placeholderB: "Team B name",
    startDebate: "Start debate",
    intro1: "Introduction team A",
    intro2: "Introduction team B",
    ref1_1: "Rebuttal 1 team A",
    ref1_2: "Rebuttal 1 team B",
    ref2_1: "Rebuttal 2 team A",
    ref2_2: "Rebuttal 2 team B",
    concl1: "Conclusion team A",
    concl2: "Conclusion team B",
    initialMinutes: "Initial time (min):",
    warningSeconds: "Warning at (sec):",
    start: "Start",
    pause: "Pause",
    reset: "Reset",
    export: "Export times to CSV",
    exportPDF: "Export results to PDF",
    timeFinished: "Time finished for",
    enterNames: "Please enter the names of both teams or participants.",
    completed: "Completed",
    yes: "Yes",
    no: "No",
    finishDebate: "Finish debate",
    debateResults: "Debate results",
    totalTime: "Total time used",
    totalOvertime: "Total overtime",
    newDebate: "New debate",
    phase: "Phase",
    timeUsed: "Time used",
    overtime: "Overtime",
    // Accessibility additions
    minute: "minute",
    minutes: "minutes",
    second: "second",
    seconds: "seconds",
    and: "and",
    timeRemaining: "Time remaining",
    warningMessage: "Warning, time is running out",
    fullScreen: "Full screen",
    exitFullScreen: "Exit full screen",
    totalCombinedTime: "Total accumulated time",
  },
  eu: {
    mainTitle: "Eskola eztabaida",
    subtitle: "ikasNOVA",
    configTitle: "Parte-hartzaileen konfigurazioa",
    labelTeamA: "A taldea / parte-hartzailea:",
    labelTeamB: "B taldea / parte-hartzailea:",
    placeholderA: "A taldearen izena",
    placeholderB: "B taldearen izena",
    startDebate: "Eztabaida hasi",
    intro1: "Sarrera A taldea",
    intro2: "Sarrera B taldea",
    ref1_1: "Ezeztapena 1 A taldea",
    ref1_2: "Ezeztapena 1 B taldea",
    ref2_1: "Ezeztapena 2 A taldea",
    ref2_2: "Ezeztapena 2 B taldea",
    concl1: "Ondorioa A taldea",
    concl2: "Ondorioa B taldea",
    initialMinutes: "Hasierako denbora (min):",
    warningSeconds: "Abisua (seg):",
    start: "Hasi",
    pause: "Gelditu",
    reset: "Berrezarri",
    export: "Denbora CSV-ra esportatu",
    exportPDF: "Emaitzak PDF-ra esportatu",
    timeFinished: "Denbora amaitu da",
    enterNames: "Mesedez, sartu bi talde edo parte-hartzaileen izenak.",
    completed: "Osatuta",
    yes: "Bai",
    no: "Ez",
    finishDebate: "Eztabaida amaitu",
    debateResults: "Eztabaidaren emaitzak",
    totalTime: "Erabilitako denbora guztira",
    totalOvertime: "Aparteko denbora guztira",
    newDebate: "Eztabaida berria",
    phase: "Fasea",
    timeUsed: "Erabilitako denbora",
    overtime: "Aparteko denbora",
    // Accessibility additions
    minute: "minutu",
    minutes: "minutu",
    second: "segundo",
    seconds: "segundo",
    and: "eta",
    timeRemaining: "Geratzen den denbora",
    warningMessage: "Abisua, denbora agortzen ari da",
    fullScreen: "Pantaila osoa",
    exitFullScreen: "Irten pantaila osotik",
    totalCombinedTime: "Metatutako denbora guztira",
  }
};

export const TIMER_CONFIGS: TimerConfig[] = [
  { id: 'intro1', defaultMinutes: 3, defaultWarning: 30, team: 'A' },
  { id: 'intro2', defaultMinutes: 3, defaultWarning: 30, team: 'B' },
  { id: 'ref1_1', defaultMinutes: 4, defaultWarning: 30, team: 'A' },
  { id: 'ref1_2', defaultMinutes: 4, defaultWarning: 30, team: 'B' },
  { id: 'ref2_1', defaultMinutes: 4, defaultWarning: 30, team: 'A' },
  { id: 'ref2_2', defaultMinutes: 4, defaultWarning: 30, team: 'B' },
  { id: 'concl1', defaultMinutes: 3, defaultWarning: 30, team: 'A' },
  { id: 'concl2', defaultMinutes: 3, defaultWarning: 30, team: 'B' },
];
